### ISSUE TITLE
How to integrate ghc of this repo into '<nixpkgs>'?

### ISSUE THREAD

**Issue by contrun** [mpickering/old-ghc-nix#1]
https://github.com/input-output-hk/haskell.nix/issues/70 is the issue I want to solve.

**Comment by mpickering** [comment]
I think this is really a question for the `haskell.nix` bug tracker but I can think of two things which might work.

1.  In your overlay override `haskell.compiler` to `nur.repos.mpickering.ghc`. This will cause every Haskell package on your system to be rebuilt locally as none will be cached.
2. When you create the package set, specify the `ghc.package` options.

```
# default.nix
let
  # Import the Haskell.nix library,
  haskell = import (builtins.fetchTarball https://github.com/input-output-hk/haskell.nix/archive/master.tar.gz) {};

  # Instantiate a package set using the generated file.
  pkgSet = haskell.mkCabalProjectPkgSet {
    plan-pkgs = import ./pkgs.nix;
    pkg-def-extras = [ ];
    modules = [ { ghc.package = nur.repos.mpickering.ghc.ghc865; }];
  };
in
  pkgSet.config.hsPkgs
```
